---
version: "3.3"
services:
  denyhosts:
    container_name: denyhosts
    restart: unless-stopped
    image: "boxrick/denyhosts-docker:latest"
    volumes:
      - /var/log/auth.log:/var/log/auth.log:ro
      - /etc/hosts.deny:/etc/hosts.deny
      - /etc/hosts.allow:/etc/hosts.allow
      #- /etc/denyhosts.conf:/etc/denyhosts.conf
