---
## Build docker image and push to dockerhub
name: build-docker

on:
  push:
    branches: main
  # Buld new version daily
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU for arm64
        uses: docker/setup-qemu-action@v2

      - name: Add buildx for arm64
        uses: docker/setup-buildx-action@v2

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: boxrick/denyhosts-docker

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          tags: boxrick/denyhosts-docker:latest

      - name: Sync readme from Github to Dockerhub
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: boxrick/denyhosts-docker
          readme: "./README.md"
